### ISSUE TITLE
[PE-D][Tester C] Functionality: Find birthday does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-2/tp#186]
![Screenshot 2023-11-03 at 5.26.25 PM.png](https://raw.githubusercontent.com/nicleongyj/ped/main/files/8ead581e-f0e1-4ffd-a6f7-dd9b1458ba6b.png)

![Screenshot 2023-11-03 at 5.26.36 PM.png](https://raw.githubusercontent.com/nicleongyj/ped/main/files/695e6a99-41ae-45e8-bffa-d251eab66529.png)

Finding the birthday 10-10 does not display the contact even though the birthday is 10/10

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nicleongyj/ped#5

**Comment by lordidiot** [comment]
Root cause seems to be due to our recent change of `Birthday::toString` which now stringifies to the date in full (`10 October`).

Also, thinking about whether we should enforce formatting for searching certain fields like Birthday.

**Comment by kokrui** [comment]
I think enforcing formatting , but I think something that could be supported for Birthday is that the search looks for both human-readable form (10 December) and DD/MM form?

**Comment by kokrui** [comment]
We realised that the UG is outdated and doesn't reflect the new human-readable birthday format, so we'll treat this as a UG functionality bug that we'll fix

<img width="702" alt="image" src="https://github.com/AY2324S1-CS2103T-T13-2/tp/assets/29654756/a9ee06c5-7041-4ce2-a288-42395904769f">
