### ISSUE TITLE
[PE-D][Tester A] Differing error messages for viewnotes with different index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-2/tp#196]
For index greater than length of contact list:
![image.png](https://raw.githubusercontent.com/Nauxe/ped/main/files/904c6e5c-0916-49d9-b3ef-a0aa16bea1cc.png)

For index smaller than length of contact list:
![image.png](https://raw.githubusercontent.com/Nauxe/ped/main/files/a720b513-e9b6-4c91-b3da-4b41a22463c9.png)

Both are invalid inputs, but their error messages are different.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Nauxe/ped#3

**Comment by limjunxian1** [comment]
this error is also persistent in `addalt`, `delete`, `updatephoto` commands which needs rectification too

**Comment by conradsoon** [comment]
> this error is also persistent in `addalt`, `delete`, `updatephoto` commands which needs rectification too

<img width="918" alt="image" src="https://github.com/AY2324S1-CS2103T-T13-2/tp/assets/18553610/2e5cfc72-166c-4ecd-a03a-17be145300fb">
Caused by this block in relevant parsers. Let's discuss a unified way to settle this.
